FROM suconghou/puppeteer:202504
RUN apk add --no-cache nss freetype freetype-dev harfbuzz ca-certificates ttf-freefont
RUN cd /usr/share/fonts/ && \
wget https://github.com/gnuletik/puppeteer-heroku-buildpack-fonts/raw/main/fonts/wqy-zenhei.ttc && \
wget https://github.com/gnuletik/puppeteer-heroku-buildpack-fonts/raw/main/fonts/wqy-microhei.ttc && \
wget https://github.com/joypixels/emojione-assets/releases/download/4.5/emojione-android.ttf && \
fc-cache -f /usr/share/fonts/
RUN cd /usr/share/fonts/ && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Light.ttf && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Medium.ttf && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Regular.ttf && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Semibold.ttf && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Thin.ttf && \
wget https://github.com/refinec/PingFangSC/raw/main/ttf/PingFangSC-Ultralight.ttf && \
fc-cache -f /usr/share/fonts/
