FROM alpine AS build
RUN apk add --update gcc g++ make curl
RUN curl -sSL https://github.com/ssb22/polipo2/archive/master.tar.gz | tar xz --strip 1 && ls -lha && \
sed -i '/^LOCAL_ROOT.*/cLOCAL_ROOT = \/' Makefile && \
sed -i '/^DISK_CACHE_ROOT*/cDISK_CACHE_ROOT = \/' Makefile
RUN CFLAGS="-Os -ffunction-sections -fdata-sections" LDFLAGS="-Wl,--gc-sections -static" make -j2 && strip -s polipo2

FROM scratch
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /polipo2 /polipo
ENTRYPOINT ["/polipo"]
CMD ["diskCacheRoot=","localDocumentRoot=","proxyAddress=0.0.0.0","serverSlots=256","serverMaxSlots=256","objectHighMark=16384","chunkHighMark=50331648"]
