FROM suconghou/haproxy AS build
RUN /usr/local/sbin/haproxy -v && ldd /usr/local/sbin/haproxy
FROM busybox
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/sbin/haproxy /usr/local/sbin/haproxy
