FROM alpine AS build
RUN apk update && apk upgrade && apk add gcc g++ make wget linux-headers pcre-dev zlib-dev openssl-dev
RUN HAPROXY_VERSION=haproxy-1.8.12 && wget --no-check-certificate https://www.haproxy.org/download/1.8/src/${HAPROXY_VERSION}.tar.gz && tar zxf ${HAPROXY_VERSION}.tar.gz && cd ${HAPROXY_VERSION} && ls -lha && \
make TARGET=linux2628 ARCH=X86_64 USE_OPENSSL=1 USE_STATIC_PCRE=1 USE_PCRE_JIT=1 USE_ZLIB=1 LDFLAGS="-s -static" ADDLIB="/usr/lib/libc.a -lz" CFLAGS="-O3" -j2 && make install && strip -s /usr/local/sbin/haproxy

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/sbin/haproxy /usr/local/sbin/haproxy
