FROM suconghou/lighttpd AS build
RUN /usr/local/sbin/lighttpd -V && ldd /usr/local/sbin/lighttpd

FROM busybox
MAINTAINER suconghou
COPY --from=build /usr/local/sbin/lighttpd /usr/local/sbin/lighttpd
EXPOSE 80
