FROM alpine AS build
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add --update gcc g++ make wget file openssl-dev openssl-libs-static pcre-dev zlib-dev zlib-static linux-headers
RUN NGINX_VERSION=nginx-1.23.0 && wget http://nginx.org/download/${NGINX_VERSION}.tar.gz && tar zxf ${NGINX_VERSION}.tar.gz && cd ${NGINX_VERSION} && \
wget -O- https://github.com/winshining/nginx-http-flv-module/archive/v1.2.10.tar.gz | tar xz && \
wget -O- https://github.com/kaltura/nginx-vod-module/archive/1.29.tar.gz | tar xz && \
./configure --with-pcre --with-pcre-jit --with-http_v2_module --with-http_ssl_module --with-http_slice_module --with-stream --with-stream_ssl_preread_module --with-file-aio --with-http_flv_module --with-http_mp4_module --add-module=nginx-http-flv-module-1.2.10 --add-module=nginx-vod-module-1.29 --sbin-path=/usr/local/sbin/nginx --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock && \
sed -i "s/-lpcre -lssl -lcrypto -lz/-static -lpcre -lssl -lcrypto -lz/g" objs/Makefile && make -j2 CFLAGS=-O3 LDFLAGS=-static && make install && \
strip -s /usr/local/sbin/nginx &&  rm -rf /etc/nginx/*.default

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/sbin/nginx /usr/local/sbin/nginx
COPY --from=build /etc/nginx /etc/nginx
COPY --from=build /var/log/nginx /var/log/nginx
RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
WORKDIR /etc/nginx
EXPOSE 80 443
