FROM alpine AS build
RUN apk update && apk upgrade && apk add gcc g++ make curl
RUN curl -sSL http://sammy.net/~sammy/hacks/redir-2.2.1.tar.gz | tar xz --strip 1 && ls -lha && \
make CFLAGS="-Os -ffunction-sections -fdata-sections" LDFLAGS="-static-libstdc++ -static-libgcc --static -Wl,-Bstatic,--gc-sections" && strip -s redir

FROM scratch
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /redir /redir
ENTRYPOINT ["/redir"]
