log:
  level: info
  production: true

plugins: 
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./accelerated-domains.china.txt"

  - tag: "black_domain"
    type: domain_set
    args:
      files:
        - "./proxy-list.txt"
        - "./gfw.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./CN-ip-cidr.txt"

  - tag: "hosts"
    type: hosts
    args:
      files:                       
        - "./hosts.txt"             

  - tag: "cache"
    type: cache
    args:
      size: 65536
      lazy_cache_ttl: 86400

  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://223.6.6.6/dns-query"
          idle_timeout: 86400
        - addr: "https://doh.360.cn/dns-query"
          idle_timeout: 86400

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://223.5.5.5/dns-query"
          idle_timeout: 86400
        - addr: "https://dns.pub/dns-query"
          idle_timeout: 86400

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
      - exec: $local_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: goto local_sequence
      - exec: goto ttl_sequence

  - tag: "hijack"
    type: sequence
    args:
      - exec: black_hole 192.168.0.3
      - exec: return


  - tag: "final"
    type: fallback
    args:
      primary: remote_sequence
      secondary: local_sequence
      threshold: 500
      always_standby: true

  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $hosts
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - matches: "qname $black_domain"
        exec: goto hijack
      - exec: $final


  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53