FROM suconghou/shadowsocks:libev AS build
RUN ls -lh /usr/local/bin/ss-server
FROM scratch
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/bin/ss-server /
ENTRYPOINT ["/ss-server"]
EXPOSE 443
