FROM suconghou/shadowsocks:libev AS build
RUN ls -lh /usr/local/bin/ss-local
FROM scratch
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/bin/ss-local /
ENTRYPOINT ["/ss-local"]
EXPOSE 443
