FROM alpine AS build
RUN wget -O- https://dl.influxdata.com/telegraf/nightlies/telegraf-static-nightly_linux_amd64.tar.gz | tar xz --strip 1

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /telegraf /usr/local/bin/
