FROM alpine AS build
RUN wget -O- https://dl.influxdata.com/chronograf/releases/chronograf-1.7.10-static_linux_amd64.tar.gz | tar xz --strip 2

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /chronoctl /usr/local/bin/
COPY --from=build /chronograf /usr/local/bin/
CMD ["chronograf"]
