FROM arm32v7/alpine AS build
RUN apk update && apk upgrade && apk add gcc g++ make cmake wget file xz bison autoconf pcre-dev zlib-dev libjpeg-turbo-dev libpng-static libpng-dev bzip2-dev openssl-dev sqlite-dev sqlite-static oniguruma-dev
RUN LIBXML2_VERSION=libxml2-2.9.10 && wget http://xmlsoft.org/sources/${LIBXML2_VERSION}.tar.gz && tar zxf ${LIBXML2_VERSION}.tar.gz && cd ${LIBXML2_VERSION} && ./configure && make -j4 && make install
RUN LIBXSLT_VERSION=libxslt-1.1.34 && wget http://xmlsoft.org/sources/${LIBXSLT_VERSION}.tar.gz && tar zxf ${LIBXSLT_VERSION}.tar.gz && cd ${LIBXSLT_VERSION} && ./configure && make -j4 && make install
RUN CURL_VERSION=curl-7.67.0 && wget --no-check-certificate https://curl.haxx.se/download/${CURL_VERSION}.tar.xz && tar Jxf ${CURL_VERSION}.tar.xz && cd ${CURL_VERSION} && ./configure && make -j4 && make install
RUN LIBFREETYPE_VERSION=freetype-2.10.1 && wget --no-check-certificate https://download-mirror.savannah.gnu.org/releases/freetype/${LIBFREETYPE_VERSION}.tar.gz && tar zxf ${LIBFREETYPE_VERSION}.tar.gz && cd ${LIBFREETYPE_VERSION} && ./configure && make -j4 && make install && ln -s $(pwd)/builds/unix/freetype-config /usr/local/bin/freetype-config
RUN LIBZIP_VERSION=libzip-1.5.2 && wget --no-check-certificate https://libzip.org/download/${LIBZIP_VERSION}.tar.xz && tar Jxf ${LIBZIP_VERSION}.tar.xz && cd ${LIBZIP_VERSION} && mkdir build && cd build && cmake .. -DBUILD_SHARED_LIBS=OFF && make -j4 && make install
RUN PHP_VERSION=php-7.4.1 && wget https://www.php.net/distributions/${PHP_VERSION}.tar.xz && tar xJf ${PHP_VERSION}.tar.xz && cd ${PHP_VERSION}
RUN REDIS_VERSION=redis-5.1.1 && cd php-7.*.* && wget https://pecl.php.net/get/${REDIS_VERSION}.tgz && tar zxf ${REDIS_VERSION}.tgz && mv ${REDIS_VERSION} ext/php-redis
RUN MSGPACK_VERSION=msgpack-2.0.3 && cd php-7.*.* && wget https://pecl.php.net/get/${MSGPACK_VERSION}.tgz && tar zxf ${MSGPACK_VERSION}.tgz && mv ${MSGPACK_VERSION} ext/msgpack
RUN IGBINARY_VERSION=igbinary-3.1.0b3 && cd php-7.*.* && wget https://pecl.php.net/get/${IGBINARY_VERSION}.tgz && tar zxf ${IGBINARY_VERSION}.tgz && mv ${IGBINARY_VERSION} ext/igbinary
RUN SWOOLE_VERSION=swoole-4.4.13 && cd php-7.*.* && wget https://pecl.php.net/get/${SWOOLE_VERSION}.tgz && tar zxf ${SWOOLE_VERSION}.tgz && mv ${SWOOLE_VERSION} ext/swoole
RUN cd php-7.*.* && rm -rf configure && ./buildconf --force && \
export CFLAGS="-Os" && LDFLAGS="-static" LIBS="$(curl-config --static-libs)" && \
export LIBZIP_LIBS="-L/usr/local/lib64 -lzip" && \
export LIBZIP_CFLAGS=-I/usr/local/include && \
./configure --enable-inline-optimization --enable-static=yes --enable-shared=no --prefix=/usr/local --with-config-file-path=/etc --without-pear --disable-cgi --disable-opcache --disable-fpm --disable-phpdbg --enable-igbinary --with-msgpack --enable-redis --enable-redis-igbinary --enable-pcntl --enable-sockets --enable-ftp --enable-bcmath --with-zip --with-zlib --enable-mbstring --enable-gd --with-freetype --with-jpeg --with-mysqli --with-pdo-mysql --enable-mysqlnd --with-openssl --enable-openssl --with-openssl-dir=/usr/ --enable-exif --enable-calendar --with-bz2 --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-xsl --with-curl=/usr/local/ && \
sed -i "s{-export-dynamic{-all-static{" Makefile && make -j4 && make install
RUN cd php-7.*.* && \
strip -s /usr/local/bin/php && mv php.ini-production /etc/php.ini && \
sed -i '/^expose_php.*/cexpose_php = Off' /etc/php.ini && sed -i '/^session.serialize_handler.*/csession.serialize_handler = igbinary' /etc/php.ini

FROM arm32v7/alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/bin/php /usr/local/bin/php
COPY --from=build /etc/php.ini /etc/php.ini
EXPOSE 9000

