FROM suconghou/php AS build
RUN /usr/local/sbin/php-fpm -v

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm
COPY --from=build /usr/local/etc/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY --from=build /usr/local/etc/php-fpm.d/ /usr/local/etc/php-fpm.d/
COPY --from=build /etc/php.ini /etc/php.ini
COPY --from=build /etc/php.ini-development /etc/php.ini-development
COPY --from=build /var/log/php-fpm /var/log/php-fpm
EXPOSE 9000
