FROM alpine AS build
RUN apk update && apk upgrade && apk add gcc g++ make wget file xz autoconf pcre-dev zlib-dev jpeg-dev libpng-dev bzip2-dev openssl-dev
RUN LIBXML2_VERSION=libxml2-2.9.8 && wget ftp://xmlsoft.org/libxml2/${LIBXML2_VERSION}.tar.gz && tar zxf ${LIBXML2_VERSION}.tar.gz && cd ${LIBXML2_VERSION} && ./configure && make -j2 && make install
RUN LIBXSLT_VERSION=libxslt-1.1.32 && wget ftp://xmlsoft.org/libxslt/${LIBXSLT_VERSION}.tar.gz && tar zxf ${LIBXSLT_VERSION}.tar.gz && cd ${LIBXSLT_VERSION} && ./configure && make -j2 && make install
RUN CURL_VERSION=curl-7.63.0 && wget --no-check-certificate https://curl.haxx.se/download/${CURL_VERSION}.tar.xz && tar Jxf ${CURL_VERSION}.tar.xz && cd ${CURL_VERSION} && ./configure && make -j2 && make install
RUN LIBFREETYPE_VERSION=freetype-2.9.1 && wget --no-check-certificate https://download.savannah.gnu.org/releases/freetype/${LIBFREETYPE_VERSION}.tar.gz && tar zxf ${LIBFREETYPE_VERSION}.tar.gz && cd ${LIBFREETYPE_VERSION} && ./configure && make && make install && ln -s $(pwd)/builds/unix/freetype-config /usr/local/bin/freetype-config
RUN IMAGEMAGICK_VERSION=7.0.8-23 && wget -O- https://github.com/ImageMagick/ImageMagick/archive/${IMAGEMAGICK_VERSION}.tar.gz | tar xz && cd ImageMagick-${IMAGEMAGICK_VERSION} && ./configure --without-threads && make -j8 && make install
RUN PHP_VERSION=php-7.2.14 && wget http://php.net/distributions/${PHP_VERSION}.tar.xz && tar xJf ${PHP_VERSION}.tar.xz && cd ${PHP_VERSION}
RUN REDIS_VERSION=redis-4.2.0 && cd php-7.*.* && wget https://pecl.php.net/get/${REDIS_VERSION}.tgz && tar zxf ${REDIS_VERSION}.tgz && mv ${REDIS_VERSION} ext/php-redis
RUN MSGPACK_VERSION=msgpack-2.0.3 && cd php-7.*.* && wget https://pecl.php.net/get/${MSGPACK_VERSION}.tgz && tar zxf ${MSGPACK_VERSION}.tgz && mv ${MSGPACK_VERSION} ext/msgpack
RUN IGBINARY_VERSION=igbinary-2.0.8 && cd php-7.*.* && wget https://pecl.php.net/get/${IGBINARY_VERSION}.tgz && tar zxf ${IGBINARY_VERSION}.tgz && mv ${IGBINARY_VERSION} ext/igbinary
RUN IMAGICK_VERSION=imagick-3.4.3 && cd php-7.*.* && wget https://pecl.php.net/get/${IMAGICK_VERSION}.tgz && tar zxf ${IMAGICK_VERSION}.tgz && mv ${IMAGICK_VERSION} ext/imagick
RUN SWOOLE_VERSION=swoole-4.2.12 && cd php-7.*.* && wget https://pecl.php.net/get/${SWOOLE_VERSION}.tgz && tar zxf ${SWOOLE_VERSION}.tgz && mv ${SWOOLE_VERSION} ext/swoole
RUN cd php-7.*.* && rm -rf configure && ./buildconf --force && \
export CFLAGS="-Os" && LDFLAGS="-static" LIBS="$(curl-config --static-libs)" && \
sed -i '/^int main(.*/cint mainhello(int argc, char **argv) { ' ext/swoole/thirdparty/hiredis/test.c && \
./configure --enable-inline-optimization --enable-static=yes --enable-shared=no --prefix=/usr/local --with-config-file-path=/etc --without-pear --disable-cgi --disable-opcache --disable-fpm --disable-phpdbg --enable-igbinary --with-msgpack --enable-redis --enable-redis-igbinary --enable-pcntl --enable-sockets --enable-ftp --enable-bcmath --enable-zip --with-zlib --enable-mbstring --with-imagick --with-gd --with-freetype-dir=/usr/local/include/freetype2/freetype --with-jpeg-dir --with-mysqli --with-pdo-mysql --with-openssl --enable-exif --enable-calendar --with-bz2 --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-xsl --with-curl=/usr/local/ && \
sed -i "s{-export-dynamic{-all-static{" Makefile && make -j8 && make install
RUN cd php-7.*.* && \
strip -s /usr/local/bin/php && mv php.ini-production /etc/php.ini && \
sed -i '/^expose_php.*/cexpose_php = Off' /etc/php.ini && sed -i '/^session.serialize_handler.*/csession.serialize_handler = igbinary' /etc/php.ini

FROM alpine
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/bin/php /usr/local/bin/php
COPY --from=build /etc/php.ini /etc/php.ini
EXPOSE 9000

