FROM suconghou/redis AS build
RUN /usr/local/bin/redis-server -v

FROM busybox
LABEL maintainer="suconghou@gmail.com"
COPY --from=build /usr/local/bin/ /usr/local/bin/
COPY --from=build /etc/redis.conf /etc/redis.conf
EXPOSE 6379
